version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '00:00'
      timezone: 'Europe/Brussels'
    allow:
      - dependency-type: production
    commit-message:
      prefix: '[DEPENDABOT]'
    labels:
      - 'dependencies'
      - 'dependabot'
    open-pull-requests-limit: 10
    reviewers:
      - 'chad-pelly'
      - 'arnedubois'
    versioning-strategy: 'increase'
