version: '2'
exclude_patterns:
  - '**/types.ts'
  - '**/*test.ts'
  - '**/__helpers__/*.ts'
  - '**/rql/parser.ts'
plugins:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 250
checks:
  argument-count:
    config:
      threshold: 5
