version: '2'
exclude_patterns:
  - '**/types.ts'
  - '**/*test.ts'
  - '**/__helpers__/*.ts'
  - 'examples'
  - 'mockType.ts'
plugins:
  duplication:
    enabled: true
    config:
      languages:
        typescript:
          mass_threshold: 250
checks:
  method-lines:
    config:
      threshold: 30
