name: Build @extrahorizon/javascript-sdk

on:
  push:
    branches-ignore:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@extrahorizon'

      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - run: yarn lint
      - run: yarn build
      - run: yarn test

