name: Publish @extrahorizon/javascript-sdk

on:
  workflow_dispatch:

  push:
    branches:
      - dev
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/gallium
          registry-url: https://npm.pkg.github.com/
          scope: '@extrahorizon'
      - run: yarn install
      - run: yarn test
      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results/

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: lts/gallium
          registry-url: https://npm.pkg.github.com/
          scope: '@extrahorizon'
      - run: yarn install
      - run: yarn build
      - run: yarn add-suffix
      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6
      - name: Print version
        run: echo ${{ steps.extract_version.outputs.version }}
      - run: git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config --global user.name "$GITHUB_ACTOR"
      - run: git tag -a v${{steps.extract_version.outputs.version}} -m "Tagging v${{steps.extract_version.outputs.version}}"
      - run: git push --tags && git push
      - run: yarn publish --registry https://npm.pkg.github.com/ --tag dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
